UBUNTU: [Packaging] depend on clang/libclang-15 for Rust
Make sure to use clang/libclang-15 for Rust, since the default
clang/libclang-16 has some build incompatibilities with gcc-13,
triggering the following error:

  BINDGEN rust/bindings/bindings_generated.rs
  thread 'main' panicked at '"ftrace_branch_data_union_(anonymous_at__/_/include/linux/compiler_types_h_146_2)" is not a valid Ident',
  +/build/rust-bindgen-0.56-DgAMvF/rust-bindgen-0.56-0.56.0/debian/vendor/proc-macro2-1.0.24/src/fallback.rs:693:9

Signed-off-by: Andrea Righi <andrea.righi@canonical.com>