UBUNTU: SAUCE: make ASYNCB_INITIALIZED available for the kernel
The flag ASYNCB_INITIALIZED is required by our driver
ubuntu/xr-usb-serial. Make it available to kernel code to prevent the
following build failure:

 ./build/ubuntu/xr-usb-serial/xr_usb_serial_common.c:1613:15: error: 'ASYNCB_INITIALIZED' undeclared (first use in this function); did you mean 'RCU_INITIALIZER'?
  1613 |  if (test_bit(ASYNCB_INITIALIZED, &xr_usb_serial->port.flags))
       |               ^~~~~~~~~~~~~~~~~~
       |               RCU_INITIALIZER

Signed-off-by: Andrea Righi <andrea.righi@canonical.com>