UBUNTU: SAUCE: Revert "tools/power turbostat: Fix 32-bit capabilities warning"
This reverts commit fcaa681c03ea82193e60d7f2cdfd94fbbcd4cae9 that seems
to break the build of turbostat with the following error:

gcc -O2 -Wall -I../../../include -DMSRHEADER='"../../../../arch/x86/include/asm/msr-index.h"' -DINTEL_FAMILY_HEADER='"../../../../arch/x86/include/asm/intel-family.h"' -D_FORTIFY_SOURCE=2 turbostat.c -o /tmp/kernel-arighi-7b3739146d49-Ial4/build/debian/build/tools-perarch/tools/power/x86/turbostat/turbostat  -lcap
turbostat.c:33:10: fatal error: sys/capability.h: No such file or directory
   33 | #include <sys/capability.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.

Revert this commit for now, since it just seems to silent a warning.

Signed-off-by: Andrea Righi <andrea.righi@canonical.com>