UBUNTU: SAUCE: usbip: ensure strings copied using strncpy are null-terminated
With gcc 9.1.0 the usbip build is failing:

  In function 'strncpy',
      inlined from 'read_usb_vudc_device' at usbip_device_driver.c:94:2:
  /usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:10: error: '__builtin_strncpy' specified bound 256 equals destination size [-Werror=stringop-truncation]

It does appear that this could legitimately end up with a string
that is not null-terminated, and that the rest of the code is
expecting a null-terminated string. Fix this to ensure strings
will always be null-terminated.

Signed-off-by: Seth Forshee <seth.forshee@canonical.com>