UBUNTU: SAUCE: media: atomisp: add missing return type (fix -Werror=return-type)
drivers/staging/media/atomisp/pci/hive_isp_css_common/host/input_system.c: In function 'input_system_configure_channel_sensor':
drivers/staging/media/atomisp/pci/hive_isp_css_common/host/input_system.c:1649:1: error: control reaches end of non-void function [-Werror=return-type]
 1649 | }
      | ^
cc1: some warnings being treated as errors

Signed-off-by: Paolo Pisati <paolo.pisati@canonical.com>