UBUNTU: SAUCE: watchdog: gxp: Add missing MODULE_LICENSE
The build system says:

ERROR: modpost: missing MODULE_LICENSE() in drivers/watchdog/gxp-wdt.o

Add the missing MODULE_LICENSE.

Signed-off-by: Nick Hawkins <nick.hawkins@hpe.com>
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
(cherry picked from https://lore.kernel.org/all/20220603131419.2948578-1-linux@roeck-us.net/)
Signed-off-by: Andrea Righi <andrea.righi@canonical.com>